### ISSUE TITLE
Almost half of the code is commented out.

### ISSUE THREAD

**Issue by KR8MER** [EMATech/Network-Studio-Clock#1]
Half the code you have posted on code.py is commented out.

**Comment by rdoursenaud** [comment]
Yeah, and?
Have you tried reading it to understand why?

Here are some hints:
- most of it has been unrolled for performance reasons or is DEBUG code that is not needed for normal execution.
- a tiny part just needs a rewrite for new CircuitPython releases and is not a crucial feature.

What else did you expect?

**Comment by KR8MER** [comment]
The issue is the code isn’t updating the RTC. It pulls the time over NTP but it isn’t being committed to the RTC.

**Comment by rdoursenaud** [comment]
Yes, I had to remove NTP since it's been broken upstream. I'm waiting for a resolution.
See adafruit/Adafruit_CircuitPython_NTP#27
